deps: update dependencies in PKGBUILDs
Currently trying to install the packages shows these errors:

```
➜  ~ doas pikaur -Sy heera-git
:: Synchronizing package databases...
 core                                                                        128.3 KiB   174 KiB/s 00:01 [##############################################################] 100%
 extra                                                                         8.3 MiB  12.2 MiB/s 00:01 [##############################################################] 100%
 community is up to date
 heera-git                                                                     3.2 KiB  7.73 KiB/s 00:00 [##############################################################] 100%

Reading repository package databases...
Reading local package database...
:: error: 'heera-git' is NOT installable.
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'plasma-framework' required by heera-calamares
:: unable to satisfy dependency 'kdbusaddons' required by heera-calamares
:: unable to satisfy dependency 'kwindowsystem' required by heera-core
:: unable to satisfy dependency 'kwindowsystem' required by heera-user-interface
:: unable to satisfy dependency 'heera-user-interface' required by heera-dock
:: unable to satisfy dependency 'kio' required by heera-system-library
:: unable to satisfy dependency 'networkmanager-qt' required by heera-system-library
:: unable to satisfy dependency 'kcoreaddons' required by heera-system-library
:: unable to satisfy dependency 'modemmanager-qt' required by heera-system-library
:: unable to satisfy dependency 'heera-system-library' required by heera-dock
:: unable to satisfy dependency 'kwindowsystem' required by heera-dock
:: unable to satisfy dependency 'kwindowsystem' required by heera-launcher
:: unable to satisfy dependency 'kwindowsystem' required by heera-qt-plugins
:: unable to satisfy dependency 'kwindowsystem' required by heera-user-interface
:: unable to satisfy dependency 'heera-user-interface' required by heera-settings
:: unable to satisfy dependency 'kio' required by heera-system-library
:: unable to satisfy dependency 'networkmanager-qt' required by heera-system-library
:: unable to satisfy dependency 'kcoreaddons' required by heera-system-library
:: unable to satisfy dependency 'modemmanager-qt' required by heera-system-library
:: unable to satisfy dependency 'kwindowsystem' required by heera-user-interface
```

These are due to the reason that many kde packages, eg. 'kio5',
'networkmanager-qt5', 'kwindowsystem5' come with kde/qt version at
end (5), which was not there earlier.

Fix the errors by updating PKGBUILDs to use new versions.

Signed-off-by: Aditya Gupta <me.adityag15@gmail.com>